name: Julia Test Matrix

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        julia-version: [1.8.1]  # Adjust Julia versions as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      - name: Build package
        uses: julia-actions/julia-buildpkg@v1

      - name: Check Secret
        env:
          SOLCAST_API_KEY: ${{ secrets.SOLCAST_API_KEY }}
        run: |
          if [ -z "$SOLCAST_API_KEY" ]; then
            echo "Secret is not set."
          else
            echo "Secret is set and its value is: $SOLCAST_API_KEY"
          fi

      - name: Run tests
        env:
          SOLCAST_API_KEY: ${{ secrets.SOLCAST_API_KEY }}
        uses: julia-actions/julia-runtest@v1